import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/utils/supabase/server';
import Navbar from '@/lib/components/navbar/navbar';
import Navlinks from '@/lib/components/navbar/dashboard/navlinks';
import UserProvider from '@/lib/providers/user-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const supabase = createClient();

  const {
    data: { user },
    error: userError
  } = await supabase.auth.getUser();

  if (userError || !user) {
    redirect('/signin');
  }

  const { data: subscription, error } = await supabase
    .from('subscriptions')
    .select('*, prices(*, products(*))')
    .in('status', ['trialing', 'active'])
    .eq('user_id', user.id)
    .maybeSingle();

  if (error) {
    console.log(error);
  }

  if (!subscription) {
    redirect('/signin');
  }

  if (user) {
    return (
      <UserProvider user={user}>
        <Navbar>
          <Navlinks />
        </Navbar>
        <main>
          {children}
        </main>
      </UserProvider>
    );
  }

  return null;
}